package com.prot_panel_hostv3.logica.clases;
// Generated 02/10/2016 21:23:21 by Hibernate Tools 4.3.1



/**
 * BasesDatos generated by hbm2java
 */
public class BasesDatos  implements java.io.Serializable {


     private int id;
     private Usuario usuario;
     private String nombre;

    public BasesDatos() {
    }

	
    public BasesDatos(int id) {
        this.id = id;
    }
    public BasesDatos(int id, Usuario usuario, String nombre) {
       this.id = id;
       this.usuario = usuario;
       this.nombre = nombre;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


