package com.prot_panel_hostv3.logica.clases;
// Generated 02/10/2016 21:23:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Dominio generated by hbm2java
 */
public class Dominio  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Set<Aplicacion> aplicacions = new HashSet<Aplicacion>(0);

    public Dominio() {
    }

	
    public Dominio(int id) {
        this.id = id;
    }
    public Dominio(int id, String nombre, Set<Aplicacion> aplicacions) {
       this.id = id;
       this.nombre = nombre;
       this.aplicacions = aplicacions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Aplicacion> getAplicacions() {
        return this.aplicacions;
    }
    
    public void setAplicacions(Set<Aplicacion> aplicacions) {
        this.aplicacions = aplicacions;
    }




}


