package logica.clases;
// Generated 02/10/2016 21:23:21 by Hibernate Tools 4.3.1


import com.prot_panel_hostv3.logica.clases.Usuario;
import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private short id;
     private String descripcion;
     private Set<Administrador> administradors = new HashSet<Administrador>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Grupo() {
    }

	
    public Grupo(short id) {
        this.id = id;
    }
    public Grupo(short id, String descripcion, Set<Administrador> administradors, Set<Usuario> usuarios) {
       this.id = id;
       this.descripcion = descripcion;
       this.administradors = administradors;
       this.usuarios = usuarios;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Administrador> getAdministradors() {
        return this.administradors;
    }
    
    public void setAdministradors(Set<Administrador> administradors) {
        this.administradors = administradors;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


