package com.prot_panel_hostv3.logica.clases;
// Generated 02/10/2016 21:23:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import com.prot_panel_hostv3.logica.clases.Aplicacion;
import logica.clases.Grupo;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private Grupo grupo;
     private String nombres;
     private String apellidos;
     private String ciudad;
     private String direccion;
     private String telefono;
     private String email;
     private String clave;
     private String directorioVirtual;


    public Usuario() {
    }

	
    public Usuario(int id) {
        this.id = id;
    }
    public Usuario(int id, Grupo grupo, String nombres, String apellidos, String ciudad, String direccion, String telefono, String email, String clave, String directorioVirtual, Set<BasesDatos> basesDatoses, Aplicacion aplicacion) {
       this.id = id;
       this.grupo = grupo;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.ciudad = ciudad;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.clave = clave;
       this.directorioVirtual = directorioVirtual;

    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getDirectorioVirtual() {
        return this.directorioVirtual;
    }
    
    public void setDirectorioVirtual(String directorioVirtual) {
        this.directorioVirtual = directorioVirtual;
    }
    




}


